export const TECHNIQUES = [
  {
    id: 'pomodoro',
    label: 'Pomodoro',
    work: 25,
    short: 5,
    long: 15,
    sessionsBeforeLong: 4,
    note: '25 min focus, 5 min break, longer break every 4 rounds.',
  },
  {
    id: 'deep-focus',
    label: 'Deep Focus',
    work: 50,
    short: 10,
    long: 20,
    sessionsBeforeLong: 3,
    note: '50 min focus, 10 min break — for dense reading or numericals.',
  },
  {
    id: '52-17',
    label: '52/17',
    work: 52,
    short: 17,
    long: 17,
    sessionsBeforeLong: 99,
    note: 'The productivity-research favourite: 52 on, 17 fully off.',
  },
  {
    id: 'ultradian',
    label: 'Ultradian',
    work: 90,
    short: 20,
    long: 20,
    sessionsBeforeLong: 99,
    note: '90 min focus matching your natural energy cycle, 20 min reset.',
  },
  {
    id: 'custom',
    label: 'Custom',
    work: 30,
    short: 5,
    long: 15,
    sessionsBeforeLong: 4,
    note: 'Set your own work and break lengths.',
  },
]
